CJA-PL-Compiler: SymbolTable Class Reference
SymbolTable Class Reference
symboltable object that stores lexemes, IDentifiers and Locations as keys.
#include <symboltable.h>
Public Member Functions
SymbolTable ()
Basic constructor.
~SymbolTable ()
int makeEntry (string)
Adds another entry to table and increases the index then returning the previous index value.
int makeEntry (string, string, string)
A new table entry is made with a predetermined name, lexeme/attribute and value of said attribute.
void addAttribute (int, string, string, string)
Assigns a new value to the lexeme at the specified location.
map< int, map< string, map
< string, string > > > get ()
Returns a copy of the current symbol table.
bool attributeExists (int, string, string)
Checks if a given entry/lexeme actually exists or not.
bool attributeValueExists (int, string, string, string)
Verify that the attribute value at the given entry matches the one the caller is examining.
string findAttributeWhere (string, string)
Searches the table for an entry with a matching lexeme and token name.
string getAttributeWhere (int, string, string)
Returns the value at the given Attribute location if it exists.
int findIndexWhere (string, string)
We find the Index of a token entry using its name and attribute.
int findLexeme (string)
Returns an integer representing the location of a lexeme, so long as it is an ID and actual lexeme.
int getNumOfReservedWords ()
Returns the reserved word count.
bool indexExists (int)
Checks if a given index is within or at the end of the symbol table.
Public Attributes
int numberOfReservedWords
We store and return the number of possible reserved words.
Private Attributes
map< int, map< string, map
< string, string > > > table
Our symbol table is a Map with a Map with a Map, called "table".
int index
An integer to index our symbol table easier.
Detailed Description
symboltable object that stores lexemes, IDentifiers and Locations as keys.
The symbol table stores its values in a Map of a Map of a Map. The values themselves are the specific keys of each kind.
It provides multiple ways to access and change inner Symbol Table data, and stores said data in a fast access form.
The structure is thus able to scale vertically and horizontally by introducing more linked maps, or storing more key values and attributes.
For reference, String Compare returns a 0 if the comparison result is fully "true".
Constructor & Destructor Documentation
SymbolTable::SymbolTable ()
Basic constructor.
Default constructor for symboltable, initializes index to 0 and sets reserved words.
We create a bunch of entries in our symbol table to reflect Reserved Words of the PL Language. The language specifies 17 particular reserved words, which we also store as an integer count. We set our index before making these entries.
References index, makeEntry(), and numberOfReservedWords.
SymbolTable::~SymbolTable () [inline]
Member Function Documentation
void SymbolTable::addAttribute (int index, string name, string attribute, string value)
Assigns a new value to the lexeme at the specified location.
Adds/Alters an attribute at a specific index, specifying token name, attribute and value.
Parameters:
index
name
attribute
value
References table.
bool SymbolTable::attributeExists (int index, string name, string attribute)
Checks if a given entry/lexeme actually exists or not.
Checks if a given attribute location exists based on an index and name.
This is separate from the lexeme's value.
It is important to note that this is not checking to see if that attribute has an actual value assigned to it, but merely that an entry that can house a value exists.
Parameters:
index
name
attribute
Returns:
bool
References table.
bool SymbolTable::attributeValueExists (int index, string name, string attribute, string value)
Verify that the attribute value at the given entry matches the one the caller is examining.
Find if an attribute value exists given the information provided.
We check if the given lexeme exists, then check if the Value of it is equivalent to the one sent by the caller (the final String "value"). Could be used for Macro shorthands, will likely be used by the Parser.
Parameters:
index
name
attribute
value
Returns:
bool
References attributeExists(), and table.
string SymbolTable::findAttributeWhere (string tokenName, string attribute)
Searches the table for an entry with a matching lexeme and token name.
Return an attribute value given the tokenName and attribute.
Returns nothing if the attribute is not found. Otherwise it returns the attribute string at that specific lexemetic location.
Not sure how useful this will be later. IF there are multiple tokens with the same attribute names then this will return the first find. Which makes me believe this wont be very useful.
Parameters:
tokenName
attribute
Returns:
attribute value on success, empty string on fail.
References attributeExists(), index, and table.
int SymbolTable::findIndexWhere (string tokenName, string attribute)
We find the Index of a token entry using its name and attribute.
Find an index using a token name and attribute name.
Not sure how useful this will be
Parameters:
tokenName
attribute
Returns:
index of found attribute, -1 on fail
References attributeExists(), and index.
int SymbolTable::findLexeme (string lexeme)
Returns an integer representing the location of a lexeme, so long as it is an ID and actual lexeme.
Finds a table entry with the given lexeme.
Otherwise, it returns -1.
This assumes the entry is an ID and attribute is a lexeme. It will return the index of the found entry, or a -1 if an entry is not found.
Returns:
int Integer representing the index of the found lexeme.
References index, and table.
map< int, map< string, map< string, string > > > SymbolTable::get ()
Returns a copy of the current symbol table.
This function returns a copy of the Table.
Returns:
std::map<int, std::map<std::string, std::map<std::string, std::string> > > Symbol Table.
References table.
string SymbolTable::getAttributeWhere (int index, string tokenName, string attribute)
Returns the value at the given Attribute location if it exists.
Returns a value at a given location if it exists.
Otherwise, we return the empty string.
Parameters:
index
tokenName
attribute
References attributeExists(), and table.
int SymbolTable::getNumOfReservedWords ()
Returns the reserved word count.
References numberOfReservedWords.
bool SymbolTable::indexExists (int index)
Checks if a given index is within or at the end of the symbol table.
Checks if the index we desire is at the end of our SymbolTable.
If empty, then our search value is the end of the Symbol Table, thus we have no entry with that index. Otherwise, an entry was found that has said index.
Returns:
bool Boolean shows whether the index exists.
References table.
int SymbolTable::makeEntry (string name, string attribute, string value)
A new table entry is made with a predetermined name, lexeme/attribute and value of said attribute.
Parameters:
name
attribute
value
References index, and table.
int SymbolTable::makeEntry (string name)
Adds another entry to table and increases the index then returning the previous index value.
An entry to the table is made with no information other than an input Name variable.
The index variable is used for the index location of the new entry, and the rest of the entry is empty. Our index is increased and the former index is returned.
Parameters:
name
References index, and table.
Member Data Documentation
int SymbolTable::index [private]
An integer to index our symbol table easier.
We use an automatically incrementing index for each entry we make, so we'll just store an auto-assigned integer within this symbol table.
int SymbolTable::numberOfReservedWords
We store and return the number of possible reserved words.
This is static and specified by the language.
map< int, map< string, map< string, string > > > SymbolTable::table [private]
Our symbol table is a Map with a Map with a Map, called "table".
We define the symbol table using a map, the key being an integer index. The second value is another map, its key being the name of the token and the value being yet another map with its key being any attribute such as "lexeme" or "type" and that map's value is the value for that attribute.
So essentially we can get an item's lexeme by using the following: table[34]["ID"]["lexeme"]
This will allow us to store any number of attributes that we need to store in the symbol table. So it would be possible to add multiple lexemes for a given word. Essentially, this is akin to storing a linked list of attribute sets in a hashmap using linear probing.
This could also be accomplished with a Vector, but Vectors scale at a worse rate than a Map.
The documentation for this class was generated from the following files:
symboltable.h
symboltable.cpp