CJA-PL-Compiler: Parser Class Reference
Parser Class Reference
The main object for Parsing the PL source code and guaranteeing correctness.
#include <parser.h>
Public Member Functions
Parser (Admin &, SymbolTable &)
Base constructor, requires the admin parent object that created it.
~Parser ()
Default Destructor.
void run ()
Runs the Parser by starting the Parse production(s) tree with the EOL $ symbol.
Token nextToken ()
Uses the Admin object to run the scanner and grab the next token, parsing when valid.
void match (string, Set)
Lexeme matching function.
void syntaxError (Set)
Outputs a syntax error message followed by the characters that would be correct.
void syntaxCheck (Set)
A function that requests an error check upon finding a character that is invalid.
bool existsError ()
Returns a TRUE if there is any kind of error.
Public Attributes
int errorCount
Keeps track of the Parsing Errors we encounter.
int labelCount
Private Member Functions
void Program (Set sts)
The following functions make up the core of our Parser, and are (in effect) essentially just a visual and literal representation of the PL language's grammar rules; each nonterminal production rule is equivalent to the calling of another one of these functions.
void Block (int, int, Set sts)
A Block grammar component, which equates to a specific program Scope.
int DefinitionPart (Set sts)
The latter half of a Block, the DefinitionPart.
int Definition (int &, Set sts)
A component Definition, which is of one of three types.
void ConstantDefinition (Set sts)
Productions for the Definition type of Constant are tested.
int VariableDefinition (int &, Set sts)
Processes a Variable according to Definition.
int VariableDefinitionPart (Set sts, int &, mType type)
Defines the definition of a VariableList, or an array.
mType TypeSymbol (Set sts)
Processes a TypeSymbol, of Boolean or Integer design.
vector< int > VariableList (Set sts, mType type, Kind kind)
Processes a variable list and guarantees a proper set of variable types.
void ProcedureDefinition (Set sts)
Defines a Procedure by name.
void StatementPart (Set sts)
Processes the StatementPart of a Block.
void Statement (Set sts)
Processes a Statement, which can be one of many.
void EmptyStatement (Set sts)
void ReadStatement (Set sts)
vector< mType > VariableAccessList (Set sts)
We need to track the various types that make up an access list.
void WriteStatement (Set sts)
vector< mType > ExpressionList (Set sts)
An Expression list can have a series of different types.
void AssignmentStatement (Set sts)
Processes an AssignmentStatement grammar component, a subpart of Statement.
void ProcedureStatement (Set sts)
Processes a subtype of Statement, a Proc.
void IfStatement (Set sts)
Verifies the If guard process.
void DoStatement (Set sts)
processes the Do guarded command.
void GuardedCommandList (int &, int, Set sts)
Matches the valid guarded commands along with the specifiers [].
void GuardedCommand (int &, int, Set sts)
Matches the guards for a GuardedCommand via Expression type check.
mType Expression (Set sts)
Checks the PrimaryExpression evals to determine Eval's type(s) Chains up to ExpressionList Returns a type resulting from the corresponding PrimaryExpression evaluations and uses a vector as (similar to SimpleExpression and Term) there is the possibility of multiple types needing comparison; This is because of the following grammar: Expression -> PrimaryExpression { PrimaryOperator PrimaryExpression }.
void PrimaryOperator (Set sts)
mType PrimaryExpression (Set sts)
A Primary Expression is a SimpleExpression with an optional operator with a simple expression.
void RelationalOperator (Set sts)
mType SimpleExpression (Set sts)
A SimpleExpression must evaluate to an Integer type and defines a simple expression.
void AddingOperator (Set sts)
mType Term (Set sts)
A Term is part of a SimpleExpression, and thus Primary Expression.
void MultiplyingOperator (Set sts)
mType Factor (Set sts)
Processes the Factor's possible productions and deterimines the correct types.
mType VariableAccess (Set sts)
The production for grabbing a Variable from a VariableAccessList.
void IndexedSelector (Set sts)
The index selector for a List, such as a VariableAccessList.
mType Constant (Set sts)
Checks validity of a Constant in an input program string.
mType Numeral (Set sts)
Guarantees that a Numeral was examined.
mType BooleanSymbol (Set sts)
Checks the validity of a Boolean at this point in the program.
mType ConstantName (Set sts)
We return the type of a constant name.
mType VariableName (Set sts)
Production for a Variable Name.
mType ProcedureName (Set sts)
The name of the Procedure is checked.
mType FactorName (Set sts)
A FactorName is a VariableAccess for resolving FACTOR productions.
void debug (string, Set, Token)
A function for printing debug parsing information to the screen.
int NewLabel ()
Private Attributes
Token currentToken
Tokens retrieved using the scanner and used in parsing heuristics.
Token lookAheadToken
Token prevToken
Admin * admin
The Parser uses the Scanner to parse the file, through a pointer to the admin class.
bool debugflag
The Debug function only processes if this Flag is set to True.
SymbolTable * table
A Symbol Table pointer, allowing direct access to Symbol Table information.
BlockTable * blocktable
A blocktable object used for proper Scope checking facilities.
string prevMatch [4]
int prevID
stack< blocktype > blockTypeStack
Used to track what area of the Block we are currently in, and thus what mType we should be returning.
int numberOfScopeTypeErrors
Tracks the Scope type of parsing errors we encounter.
Detailed Description
The main object for Parsing the PL source code and guaranteeing correctness.
The Parser is responsible for verifying that the syntax in a PL program's source code is semantically correct. It verifies/guarantees that a program corresponds to the correct series of Production Rules of the PL grammar, but correspondingly guarantees that the scope and type checking rules, or rather, the implicit rules of the grammar are also adhered to.
The Function Call tree that is generated corresponds to the outline for a correct Parse tree for the PL grammar, and thus an incorrect program will break this tree at some point, in some fashion.
Every function call corresponds to a PL production or a corrected PL production set (adjusted for ambiguity or problems when present).
The Parser uses a BlockTable to ensure that the scope and type rules are valid when parsing a given statement. This is done by ensuring that the scope of an "entry" is correct or "new", and that all following usages of a declaration are verified in kind.
Constructor & Destructor Documentation
Parser::Parser (Admin & adminObject, SymbolTable & symTable)
Base constructor, requires the admin parent object that created it.
Constructor for Parser object class.
Binds the external admin object locally, controls the debug status and sets the initial lookahead token/scanner var position.
Parameters:
adminObject a reference to the parent Admin object.
References admin, blocktable, debugflag, errorCount, labelCount, lookAheadToken, nextToken(), numberOfScopeTypeErrors, and table.
Parser::~Parser ()
Default Destructor.
Base destructor.
Member Function Documentation
void Parser::AddingOperator (Set sts) [private]
References debug(), Token::getLexeme(), lookAheadToken, match(), and syntaxCheck().
void Parser::AssignmentStatement (Set sts) [private]
Processes an AssignmentStatement grammar component, a subpart of Statement.
Uses two vectors of mTypes to match up to Variable and Expression lists, and guarantee their types match correspondingly, or outputs a type mismatch error therein.
References admin, blocktable, BOOLEAN, CBOOLEAN, CINTEGER, BlockTable::convertType(), debug(), Admin::emit2(), ExpressionList(), First::ExpressionList(), Admin::getColumnNumber(), Admin::getLineNumber(), INTEGER, lookAheadToken, match(), Set::munion(), numberOfScopeTypeErrors, syntaxCheck(), and VariableAccessList().
void Parser::Block (int beginLabel, int varLabel, Set sts) [private]
A Block grammar component, which equates to a specific program Scope.
Each Block contains a DefinitionPart and StatementPart, and indicates that a new program Scope has been entered. Thus, the internal parts have access to the previous Block entries (scope data) but the StatementPart AFTER this block (if any) will not have access to the information created in this Block production (we use endBlock to ensure this.)
A new scope has started.
The previous scope (block) has ended.
References admin, blocktable, debug(), DefinitionPart(), First::DefinitionPart(), Admin::emit2(), Admin::emit3(), BlockTable::endBlock(), lookAheadToken, match(), Set::munion(), BlockTable::newBlock(), StatementPart(), First::StatementPart(), and syntaxCheck().
mType Parser::BooleanSymbol (Set sts) [private]
Checks the validity of a Boolean at this point in the program.
Ensures the next token is proper for a boolean of some sort, then returns a BOOLEAN mType for our semantic analysis.
Makes sure our proceeding tokens are correct for a boolean expression.
Ensures that the Parser knows that a Boolean was evaluated.
References BOOLEAN, debug(), Token::getLexeme(), lookAheadToken, match(), and syntaxCheck().
mType Parser::Constant (Set sts) [private]
Checks validity of a Constant in an input program string.
Either in a constantDefinition or an Array definition, Can be a Numeral, BooleanSymbol or ConstantName
A constant can be one of multiple types, and thus we check which one while checking the validity and let that mtype information chain upwards.
Create firstsets of the possibilities of a Constant.
Check for validity of the matching token, which is one of these...
then we return the given matching type.
References admin, blockTypeStack, BooleanSymbol(), ConstantName(), debug(), Admin::emit2(), Token::getLexeme(), Token::getValue(), Set::isMember(), lookAheadToken, Numeral(), STATEMENTPART, and syntaxCheck().
void Parser::ConstantDefinition (Set sts) [private]
Productions for the Definition type of Constant are tested.
Consists of "const" ConstantName "=" Constant ->
Thus, we check to make sure each component is value, and check the Constant and ConstantName productions.
Here, is where we check to see that the Constant information does not exist in our scope already, and generate an error if it does.
References admin, blocktable, BOOLEAN, Constant(), CONSTANT, First::Constant(), ConstantName(), First::ConstantName(), debug(), BlockTable::define(), BlockTable::find(), Admin::getColumnNumber(), Token::getLexeme(), Admin::getLineNumber(), Token::getValue(), INTEGER, lookAheadToken, match(), Set::munion(), numberOfScopeTypeErrors, TableEntry::okind, TableEntry::otype, syntaxCheck(), UNIVERSAL, and TableEntry::value.
mType Parser::ConstantName (Set sts) [private]
We return the type of a constant name.
We're in the definition part at this point, and thus defining the const in its name.
References debug(), lookAheadToken, syntaxCheck(), and VariableName().
void Parser::debug (string functionName, Set sts, Token nextToken) [private]
A function for printing debug parsing information to the screen.
Parsing Debug information output function.
This function takes the Function Name (a string), a given Set and a Token as an input, and outputs them in a readable form.
Outputs the current parsing information as a form of debugging information. The function name is grabbed from the __func__ C++ macro.
Parameters:
functionName The name of the function caller.
sts The current stack's stop set.
nextToken The next token being parsed.
References admin, debugflag, Admin::getColumnNumber(), and Admin::getLineNumber().
int Parser::Definition (int & varStart, Set sts) [private]
A component Definition, which is of one of three types.
No special type checking or scope rules occurs here, but rather, in one of the proceeding functions.
A Definition can be one of these three types: Constant, Variable or Procedure; an array is of type Variable, of course.
See also:
DefinitionPart()
We simply check which kind of Definition the next token belongs to.
References ConstantDefinition(), First::ConstantDefinition(), debug(), Token::getLexeme(), lookAheadToken, ProcedureDefinition(), First::ProcedureDefinition(), syntaxCheck(), VariableDefinition(), and First::VariableDefinition().
int Parser::DefinitionPart (Set sts) [private]
The latter half of a Block, the DefinitionPart.
The DefinitionPart is where PL constructs are first declared, though only given distinct values in the cases of Proc names, Const values, and array sizes.
The block type is recorded to ensure that Expressions and guards evaluate properly.
Used to guarantee that the proceeding productions have the right semantic types when checked.
Loops through until we find a Token that isn't a valid Definition/is the end of the DefinitionPart
Since we are no longer in the DefinitionPart, we pop it off the Type stack.
References blockTypeStack, debug(), First::Definition(), Definition(), DEFINITIONPART, Token::getLexeme(), Set::isMember(), lookAheadToken, match(), Set::munion(), and syntaxCheck().
void Parser::DoStatement (Set sts) [private]
processes the Do guarded command.
Part of guaranteeing the Guards are correct. Matches the relevent guards checks that the subsequent guarded command list is valid.
References admin, debug(), Admin::emit2(), GuardedCommandList(), First::GuardedCommandList(), lookAheadToken, match(), Set::munion(), NewLabel(), and syntaxCheck().
void Parser::EmptyStatement (Set sts) [private]
References debug(), lookAheadToken, match(), and syntaxCheck().
bool Parser::existsError ()
Returns a TRUE if there is any kind of error.
Returns a true if any errors of any kind are found.
References errorCount, and numberOfScopeTypeErrors.
mType Parser::Expression (Set sts) [private]
Checks the PrimaryExpression evals to determine Eval's type(s) Chains up to ExpressionList Returns a type resulting from the corresponding PrimaryExpression evaluations and uses a vector as (similar to SimpleExpression and Term) there is the possibility of multiple types needing comparison; This is because of the following grammar: Expression -> PrimaryExpression { PrimaryOperator PrimaryExpression }.
References admin, BOOLEAN, CBOOLEAN, CINTEGER, debug(), Admin::emit1(), Token::getLexeme(), INTEGER, Set::isMember(), lookAheadToken, Set::munion(), First::PrimaryExpression(), PrimaryExpression(), PrimaryOperator(), First::PrimaryOperator(), syntaxCheck(), and UNIVERSAL.
vector< mType > Parser::ExpressionList (Set sts) [private]
An Expression list can have a series of different types.
Evaluates a list of Expressions for use by Statements.
Grabs all of the types of the expression(s) and stores them in a vector, which is later returned.
References debug(), First::Expression(), Expression(), Token::getLexeme(), lookAheadToken, match(), Set::munion(), and syntaxCheck().
mType Parser::Factor (Set sts) [private]
Processes the Factor's possible productions and deterimines the correct types.
Calls FactorName instead of VariableName, to remove an ambiguity. Determines the type of Factor and returns it, or an error.
* * * * *
FIX TO 1 BY REMOVING THE -1 ALSO IN FACTOR NAME. ED is currently starting at 1, but we think el should start at 1 but it starts at 0. We would have to change - , +, AND, OR, >, < possibly to the post-fix form. Also EQUALS *
References admin, blocktable, First::Constant(), Constant(), BlockTable::currentLevel(), debug(), TableEntry::displacement, Admin::emit1(), Admin::emit3(), Expression(), First::Expression(), First::Factor(), FactorName(), First::FactorName(), BlockTable::find(), Token::getLexeme(), Token::getValue(), TableEntry::level, lookAheadToken, match(), Set::munion(), TableEntry::okind, syntaxCheck(), VARIABLE, and VariableAccess().
mType Parser::FactorName (Set sts) [private]
A FactorName is a VariableAccess for resolving FACTOR productions.
Returns the given type of the factor (numeral, boolean or universal). Alternatively, if the next token is a VariableName, it grabs the type that said Variable corresponds to.
If it's a name, grab its type, and process the index if it's an array
Otherwise, it's either a Numeral or a Boolean symbol type. Process them.
References admin, blocktable, BooleanSymbol(), First::BooleanSymbol(), First::Constant(), BlockTable::currentLevel(), debug(), TableEntry::displacement, Admin::emit1(), Admin::emit3(), BlockTable::find(), Token::getLexeme(), Admin::getLineNumber(), Token::getValue(), IndexedSelector(), First::IndexedSelector(), Set::isMember(), TableEntry::level, lookAheadToken, Set::munion(), Numeral(), First::Numeral(), TableEntry::size, syntaxCheck(), First::VariableAccess(), and VariableName().
void Parser::GuardedCommand (int & thisLabel, int GoTo, Set sts) [private]
Matches the guards for a GuardedCommand via Expression type check.
Brief...then evaluates the StatementPart of a Guarded command (do ..., if ...) If the expression type is not a Boolean, then it throws the proper error. Does not chain up.
References admin, BOOLEAN, CBOOLEAN, debug(), Admin::emit2(), Expression(), Admin::getColumnNumber(), Admin::getLineNumber(), lookAheadToken, match(), Set::munion(), NewLabel(), numberOfScopeTypeErrors, StatementPart(), First::StatementPart(), and syntaxCheck().
void Parser::GuardedCommandList (int & startLabel, int GoTo, Set sts) [private]
Matches the valid guarded commands along with the specifiers [].
Verifies that the GuardedCommands are valid, and each subsequent guarded command in the list is valid as well.
References debug(), Token::getLexeme(), First::GuardedCommand(), GuardedCommand(), lookAheadToken, match(), Set::munion(), and syntaxCheck().
void Parser::IfStatement (Set sts) [private]
Verifies the If guard process.
Checks for proper If components, while calling for a possible GuardedCommandList
References admin, debug(), Admin::emit2(), Admin::getLineNumber(), GuardedCommandList(), First::GuardedCommandList(), lookAheadToken, match(), Set::munion(), NewLabel(), and syntaxCheck().
void Parser::IndexedSelector (Set sts) [private]
The index selector for a List, such as a VariableAccessList.
We check to ensure that the list accessor has the specified symbols ([_]) An indexed selector is composed of [ EXPRESSION ]. Chains up to VariableAccessList through VariableAccess.
Determine the type of expression for this selector.
the Indexed Selector is not an integer or constant integer, and thus is not valid!
References admin, blocktable, CINTEGER, BlockTable::convertType(), debug(), Expression(), First::Expression(), Admin::getColumnNumber(), Admin::getLineNumber(), INTEGER, lookAheadToken, match(), Set::munion(), numberOfScopeTypeErrors, and syntaxCheck().
void Parser::match (string matchMe, Set validNextCharacters)
Lexeme matching function.
The Parser's lexeme Matching function.
Uses a set object consisting of the next possible valid lexemes to check of matched character is valid, and outputs an error otherwise.
Parameters:
matchMe The string lexeme to be matched.
validNextCharacters The set of characters that represent a valid match.
Matches the input lexeme to that of the next token. Otherwise, we generate and error. Finally, we check for a valid syntax set.
Parameters:
matchMe A lexeme that we wish to check for a match for validity.
validNextCharacters A set of characters that would be a "valid" next input.
References debug(), Token::getLexeme(), lookAheadToken, nextToken(), syntaxCheck(), and syntaxError().
void Parser::MultiplyingOperator (Set sts) [private]
References debug(), Token::getLexeme(), lookAheadToken, match(), and syntaxCheck().
int Parser::NewLabel () [private]
References labelCount.
Token Parser::nextToken ()
Uses the Admin object to run the scanner and grab the next token, parsing when valid.
Function that advances the scanner until a valid input is found.
Loops the tokenizer until a non-bad/non-newline/non-comment token is found. Returns a token, possibly blank.
References admin, BADNUMERAL, BADSYMBOL, COMMENT, Token::getType(), NEWLINE, and Admin::nextToken().
mType Parser::Numeral (Set sts) [private]
Guarantees that a Numeral was examined.
Checks for the proper lookahead for a Numeral stop set.
We have evaluated an INTEGER literal.
References debug(), INTEGER, lookAheadToken, match(), and syntaxCheck().
mType Parser::PrimaryExpression (Set sts) [private]
A Primary Expression is a SimpleExpression with an optional operator with a simple expression.
Checks to make sure that the proper evaluations occur for a SimpleExpression; One must evaluate to a boolean, but with multiples, it could be comparative, or equivalency. Thus we check to see what type of Factors are resultant from the simpleexpression terms.
We've come to a functional specifier, so we'll either return a boolop if the factor is valid, or an error type.
It's a SimpleExpression akin to a term-kind of some sort, so we'll check the corresponding production types.
a relational operator follows the first SimpleExpression, thus we know that we will have to have int comparisons rather than returning a boolean
Clarify that, since there are two SimpleExpressions, that their types are comparable in terms of boolean ops
References admin, BOOLEAN, CBOOLEAN, CINTEGER, debug(), Admin::emit1(), Factor(), Token::getLexeme(), INTEGER, Set::isMember(), lookAheadToken, Set::munion(), RelationalOperator(), First::RelationalOperator(), First::SimpleExpression(), SimpleExpression(), syntaxCheck(), and UNIVERSAL.
void Parser::PrimaryOperator (Set sts) [private]
References debug(), Token::getLexeme(), lookAheadToken, match(), and syntaxCheck().
void Parser::ProcedureDefinition (Set sts) [private]
Defines a Procedure by name.
Defines the Procedure and processes its name accordingly. Adds it to the current/given block.
References admin, Block(), First::Block(), blocktable, debug(), BlockTable::define(), Admin::emit1(), Admin::emit2(), Admin::emit3(), Token::getValue(), lookAheadToken, match(), Set::munion(), NewLabel(), PROCEDURE, ProcedureName(), First::ProcedureName(), syntaxCheck(), and UNIVERSAL.
mType Parser::ProcedureName (Set sts) [private]
The name of the Procedure is checked.
A type evaluated from a VariableName is returned. A procedure's name is a string and should correspond to a variable name.
References debug(), lookAheadToken, syntaxCheck(), and VariableName().
void Parser::ProcedureStatement (Set sts) [private]
Processes a subtype of Statement, a Proc.
Checks to see if the Procedure exists in a previous Scope/Block. If not, then the call was invalid/procname does not match or exist, otherwise it just returns the command properly.
References admin, blocktable, BlockTable::convertKind(), BlockTable::convertType(), BlockTable::currentLevel(), debug(), Admin::emit3(), BlockTable::find(), Admin::getColumnNumber(), Admin::getLineNumber(), Token::getValue(), TableEntry::level, lookAheadToken, match(), Set::munion(), numberOfScopeTypeErrors, TableEntry::okind, TableEntry::otype, PROCEDURE, ProcedureName(), First::ProcedureName(), TableEntry::startLabel, and syntaxCheck().
void Parser::Program (Set sts) [private]
The following functions make up the core of our Parser, and are (in effect) essentially just a visual and literal representation of the PL language's grammar rules; each nonterminal production rule is equivalent to the calling of another one of these functions.
The following is a set of Production-Rule functions.
For each of these, refer to the Parser.cpp heading comments.
In order to guarantee that our Productions are satisfying the various Type checking requirements of the PL language, we need to make sure that they evaluate to - or return - or operate on the proper type of expression or terminal or nonterminal set (at the very basest of levels, these end of being roughly equivalent).
Thus, we return an mType or a vector of mType (for lists) in order to guarantee that the proper evaluation or comparison has occured, or in order to check if the following or preceding evaluations are correct.
For each of the following, refer to the PL grammar. Any deviations indicate a correction of the grammar to eliminate the problems of Ambiguity or implicit differentiation. In any case, the role of each function is explicit within the function's name itself.
Pages 282-287 of Per Brinch Hansen's Pascal Compiler book.
See also:
parser.cpp, blocktable.h
Each one has a specific speciality in regards to how they treat their input and production rules, but on the whole they follow a key process:
1) Output the function name and data. 2) Choose a production rule to follow based off of the lookahead 3) Try to Match any prerequisite statements or rules 4) Append any valid lexemes to the StopSet sts 5) Choose a production rule and follow it (a non-terminal) 6) Repeat ~3-5 unless an error is found 7) Attempt to match the post-requisite statement/lexeme/rule. 8) Check the validity of the lookahead in regards to the stopset sts
This implicitly maintains a "stack" of unique stopsets at each function (production) level, These are allocated on the application stack.
Thus, we need to be wary of Stack Overflows when using the recursive parser.
In order to guarantee Semantic correctness and correct Scope validity, some productions need to return their mType or the mType of their proceeding operations which is then compared against the set of proper possible mTypes for the given production rules to guarantee that it's valid.
i.e. we cannot have Integer X := 5 in the DefinitionPart. For scope checking, we check the current and preceeding blocks to see if the currently examined table entry/tokenized object is semantically valid and not being redeclared or improperly used. The order and syntax of such operations varies with each specific production, and thus does not fit into the 8-point checklist above.
See also:
parser.h The root production of A PL program, the Program production.
The PL program should start here, and ends with the ./$ sign set. From here, the first, base Block is created and called.
References admin, Block(), debug(), Admin::emit1(), Admin::emit3(), lookAheadToken, match(), Set::munion(), NewLabel(), and syntaxCheck().
void Parser::ReadStatement (Set sts) [private]
References admin, debug(), Admin::emit2(), lookAheadToken, match(), Set::munion(), syntaxCheck(), VariableAccessList(), and First::VariableAccessList().
void Parser::RelationalOperator (Set sts) [private]
References debug(), Token::getLexeme(), lookAheadToken, match(), and syntaxCheck().
void Parser::run ()
Runs the Parser by starting the Parse production(s) tree with the EOL $ symbol.
The main Runner for the Parser object.
Sets the $ marker for the file as a stopset value. This ensures that $ does not get recognized as a syntax error and that any matches that happen to include a $ will be correct. The initial grammar prod., Program, is parsed (executed with sts).
References errorCount, numberOfScopeTypeErrors, and Program().
mType Parser::SimpleExpression (Set sts) [private]
A SimpleExpression must evaluate to an Integer type and defines a simple expression.
A vector of mTypes is used because a SimpleExpression is like a Term; One or Many of its subcomponents. A SimpleExpression is composed of Multiple terms, a possible sub operator, and multiple Adding operators correspondingly. Thus, we verify that the terms and operator types evaluate properly, and return the corresponding result.
Vector to track the subcomponent types.
References AddingOperator(), First::AddingOperator(), admin, BOOLEAN, CBOOLEAN, CINTEGER, debug(), Admin::emit1(), Token::getLexeme(), INTEGER, lookAheadToken, match(), Set::munion(), syntaxCheck(), Term(), First::Term(), and UNIVERSAL.
void Parser::Statement (Set sts) [private]
Processes a Statement, which can be one of many.
Processes possible statements, only one input to many possibilities.
References AssignmentStatement(), debug(), DoStatement(), EmptyStatement(), Token::getLexeme(), IfStatement(), Set::isMember(), lookAheadToken, ProcedureStatement(), ReadStatement(), syntaxCheck(), and WriteStatement().
void Parser::StatementPart (Set sts) [private]
Processes the StatementPart of a Block.
Adds StatementPart to the blocktype stack and calls the statementpart productions (statement). Pops accordingly after successful parsing.
References blockTypeStack, debug(), Token::getLexeme(), lookAheadToken, match(), Set::munion(), Statement(), First::Statement(), STATEMENTPART, and syntaxCheck().
void Parser::syntaxCheck (Set validNextCharacters)
A function that requests an error check upon finding a character that is invalid.
Checks if the next Token (its lexeme) is of a valid set of characters.
This can only happen after having followed a Valid input character.
Checks if the the lexeme of the nlookahead/next token is in the set of valid characters, and generates a Syntax Error if they are not. That is, if the next character isn't valid, then there's a syntax error.
References Token::getLexeme(), Set::isMember(), lookAheadToken, and syntaxError().
void Parser::syntaxError (Set validNextCharacters)
Outputs a syntax error message followed by the characters that would be correct.
Cleans up after an error has been detected while matching or checking syntax.
syntaxError will loop until it finds the next valid character after finding an error.
Parameters:
validNextCharacters The set of valid next characters as indicated by the grammar.
14240815
Increases the error count, outputs the relevent error information, then loops until it encounters a valid set of next parseable characters.
References admin, currentToken, errorCount, Admin::getColumnNumber(), Token::getLexeme(), Admin::getLineNumber(), Set::isMember(), lookAheadToken, nextToken(), and Set::toString().
mType Parser::Term (Set sts) [private]
A Term is part of a SimpleExpression, and thus Primary Expression.
A term can actually be a logical series of Terms, as they occur over multiple expressions. Thus, we need to keep track of them in an mType vector.
Eventually, this chains back up to SimpleExpression, then PrimaryExpression, then Expression. The Term is a core/central production language grammar component.
Term = Factor { MultiplyingOperator Factor }.
A vector of types to account for a series of terms.
We grab the relevant Term mType from a Factor, the base of a Term production
Used to grab the proper Multiplicative symbol for ASSEM output.
If we have a qualifying MultiplyingOperator, then we keep adding the Factor terms to the mType vector until we are no longer processing Term components.
See also:
Term-Grammar Production.
We output after the pushback with FACTOR in order to get the postfix form.
References admin, BOOLEAN, CBOOLEAN, CINTEGER, debug(), Admin::emit1(), First::Factor(), Factor(), Token::getLexeme(), INTEGER, lookAheadToken, MultiplyingOperator(), First::MultiplyingOperator(), Set::munion(), syntaxCheck(), and UNIVERSAL.
mType Parser::TypeSymbol (Set sts) [private]
Processes a TypeSymbol, of Boolean or Integer design.
Returns a an mType from a typesymbol, Checks the lookahead and returns the valid type (int or bool) or returns a UNIVERSAL (error) type.
References BOOLEAN, debug(), Token::getLexeme(), INTEGER, lookAheadToken, match(), syntaxCheck(), and UNIVERSAL.
mType Parser::VariableAccess (Set sts) [private]
The production for grabbing a Variable from a VariableAccessList.
We check to make sure that the index selector is valid, then chain up the type from the given VariableName.
Set the index selector stop set.
Grab the proper type from the variable name.
Process the indexedSelector data, if valid.
References admin, blocktable, BlockTable::currentLevel(), debug(), TableEntry::displacement, Admin::emit3(), BlockTable::find(), Token::getLexeme(), Admin::getLineNumber(), Token::getValue(), First::IndexedSelector(), IndexedSelector(), Set::isMember(), TableEntry::level, lookAheadToken, Set::munion(), TableEntry::size, syntaxCheck(), and VariableName().
vector< mType > Parser::VariableAccessList (Set sts) [private]
We need to track the various types that make up an access list.
Processes a list of VariableAccess productions.
Returns a vector of the corresponding types of variableaccess vars.
References debug(), Token::getLexeme(), lookAheadToken, match(), Set::munion(), syntaxCheck(), First::VariableAccess(), and VariableAccess().
int Parser::VariableDefinition (int & varStart, Set sts) [private]
Processes a Variable according to Definition.
Grabs the type of an input symbol and passes it to the VariableDefinitionPart. This allows us to properly process Arrays or standard VARIABLEs and attach them to the blocktable and block and current scope as required, while checking their components (such as the array index specifier) accordingly.
References debug(), lookAheadToken, Set::munion(), syntaxCheck(), TypeSymbol(), VariableDefinitionPart(), and First::VariableDefinitionPart().
int Parser::VariableDefinitionPart (Set sts, int & varStart, mType type) [private]
Defines the definition of a VariableList, or an array.
Array as defined; "array" VariableList "[" Constant "]" or it's just VariableList
Guarantees that the valid prodution is chosed by examining the type of the variable and the corresponding sets resultant from the lookahead.
Checks the validity of Array components if necessary, and creates the Array to specification within the BlockTable.
References admin, ARRAY, blocktable, Constant(), First::Constant(), BlockTable::convertType(), debug(), BlockTable::find(), Admin::getColumnNumber(), Token::getLexeme(), Admin::getLineNumber(), Token::getValue(), INTEGER, lookAheadToken, match(), Set::munion(), numberOfScopeTypeErrors, TableEntry::otype, BlockTable::redefineSize(), syntaxCheck(), TableEntry::value, VARIABLE, VariableList(), and First::VariableList().
vector< int > Parser::VariableList (Set sts, mType type, Kind kind) [private]
Processes a variable list and guarantees a proper set of variable types.
Checks for variables as it creates their block and table entries, and returns a vector of their ids.
References admin, blocktable, BlockTable::convertKind(), debug(), BlockTable::define(), SymbolTable::getAttributeWhere(), Admin::getColumnNumber(), Token::getLexeme(), Admin::getLineNumber(), Token::getValue(), Set::isMember(), lookAheadToken, match(), Set::munion(), numberOfScopeTypeErrors, syntaxCheck(), BlockTable::table, First::VariableName(), and VariableName().
mType Parser::VariableName (Set sts) [private]
Production for a Variable Name.
We either define a new Const/Proc/Array variable type (Universal), or we check for the variable's existence (as the only other access is in a statement). If it does not exist, then we're using an undeclared name. Otherwise, we determine and return the variable's type to the previous production.
We set the type of a VariableName by checking the kind of variable and its corresponding entry's oType. I.e. A constant Integer. If we're in the definition part, it's of a Universal type. Otherwise, we search for it...if it isn't found, then we're using an undeclared variable.
The variable was not found, and we're not declaring it for the first time, so it's an error.
Return whatever type we have. Universal is the stock type when we encounter an error.
References admin, blocktable, blockTypeStack, BOOLEAN, CBOOLEAN, CINTEGER, CONSTANT, debug(), DEFINITIONPART, Admin::emit2(), BlockTable::find(), Admin::getColumnNumber(), Admin::getLineNumber(), Token::getValue(), INTEGER, lookAheadToken, match(), numberOfScopeTypeErrors, TableEntry::okind, TableEntry::otype, STATEMENTPART, syntaxCheck(), UNIVERSAL, and TableEntry::value.
void Parser::WriteStatement (Set sts) [private]
References admin, debug(), Admin::emit2(), ExpressionList(), First::ExpressionList(), lookAheadToken, match(), Set::munion(), and syntaxCheck().
Member Data Documentation
Admin* Parser::admin [private]
The Parser uses the Scanner to parse the file, through a pointer to the admin class.
BlockTable* Parser::blocktable [private]
A blocktable object used for proper Scope checking facilities.
See also:
blocktable.h
stack<blocktype> Parser::blockTypeStack [private]
Used to track what area of the Block we are currently in, and thus what mType we should be returning.
Token Parser::currentToken [private]
Tokens retrieved using the scanner and used in parsing heuristics.
bool Parser::debugflag [private]
The Debug function only processes if this Flag is set to True.
int Parser::errorCount
Keeps track of the Parsing Errors we encounter.
int Parser::labelCount
Token Parser::lookAheadToken [private]
int Parser::numberOfScopeTypeErrors [private]
Tracks the Scope type of parsing errors we encounter.
int Parser::prevID [private]
string Parser::prevMatch[4] [private]
Token Parser::prevToken [private]
SymbolTable* Parser::table [private]
A Symbol Table pointer, allowing direct access to Symbol Table information.
The documentation for this class was generated from the following files:
parser.h
parser.cpp