CJA-PL-Compiler: Token Class Reference
Token Class Reference
Token object that is made up of a lexeme (string), a value (integer) and a Type.
#include <token.h>
Public Member Functions
Token ()
A base constructor for the Token class.
~Token ()
Token (Type, int, string)
A special Token constructor, which we give it the Token data immediately.
const int getValue () const
A set of accessors for returning the bare lexical data of the Token.
const Type getType () const
const string getLexeme () const
void setType (Type)
A set of modifiers to change the Token's atomic data types.
void setValue (int)
void setLexeme (string)
string toString ()
Converts the Token to a String in the form of <_,_,_>
bool operator== (const Token &) const
Overloaded operators to allow easy comparison between two tokens.
bool operator!= (const Token &) const
Redefined Non-Equivalency Operator for a Token.
Protected Attributes
int value
We put the core Token values in a protected state in case we wish to subclass token.
Type type
string lexeme
Detailed Description
Token object that is made up of a lexeme (string), a value (integer) and a Type.
The Token is the Strong/multivalued base type that is used by our Scanner, Parser and their communicable Symbol Table.
It provides accessors and mutators for the associated value types. The Token itself is represented by a "< token-type, token-value, token-lexeme >" format.
Constructor & Destructor Documentation
Token::Token ()
A base constructor for the Token class.
The default constructor, which assigns basic null-like values to the token.
Destructor unspecified.
See also:
Token::Token() Definition.
References lexeme, type, UNKNOWN, and value.
Token::~Token () [inline]
Token::Token (Type newType, int newValue, string newLexeme)
A special Token constructor, which we give it the Token data immediately.
Creates a Token with a specified type, value and lexeme.
Used when reconstructing the tokens.
A Token is constructed from the values given by the constructor parameters.
Parameters:
newType The given Type of token (if known).
newValue The value of our lexeme (if any).
newLexeme A string representing our Lexeme name.
References lexeme, type, and value.
Member Function Documentation
const string Token::getLexeme () const
References lexeme.
const Type Token::getType () const
References type.
const int Token::getValue () const
A set of accessors for returning the bare lexical data of the Token.
Return Functions give access to atomic Token data to outside actors.
References value.
bool Token::operator!= (const Token & temp) const
Redefined Non-Equivalency Operator for a Token.
Returns the inverse of the equivalency operator.
Parameters:
temp A token reference that we compare this one to.
Returns:
a boolean indicating that it is equivalent (false) or not.
bool Token::operator== (const Token & first) const
Overloaded operators to allow easy comparison between two tokens.
Redefined Equivalency Operator for a Token.
Defines the equivalency operator as a comparison between the lexeme, the value and the type of this token and the one it is compared to.
Parameters:
first A token reference that we compare this one to.
Returns:
a boolean indicating that it is equivalent (true) or not.
References getLexeme(), getType(), and getValue().
void Token::setLexeme (string newLexeme)
References lexeme.
void Token::setType (Type newType)
A set of modifiers to change the Token's atomic data types.
A set of mutators allow us to alter our Token data after construction.
References type.
void Token::setValue (int newValue)
References value.
string Token::toString ()
Converts the Token to a String in the form of <_,_,_>
Returns a string representation of a token.
See also:
Token{};.
Token Data is transformed into a string of the format: "< token-type, token-value, token-lexeme >" and returned as a string.
Returns:
string A string representing our token.
References lexeme, spellOutTypeName(), type, and value.
Member Data Documentation
string Token::lexeme [protected]
Type Token::type [protected]
int Token::value [protected]
We put the core Token values in a protected state in case we wish to subclass token.
The documentation for this class was generated from the following files:
token.h
token.cpp