CJA-PL-Compiler: Scanner Class Reference
Scanner Class Reference
Scanner object reads chars, constructs tokens and contributes to parser/symboltable.
#include <scanner.h>
Public Member Functions
Scanner (SymbolTable &, Admin &)
There should only be this one kind of constructor.
~Scanner ()
Basic, empty destructor.
Token nextToken ()
Goes to the next token and attempts to handle it; otherwise, it grabs the appropriate handler.
void loadSource (string &)
Links the Scanner's "source" string to the original PL source code File from main.
void scan ()
Unused internal Scanning function.
string getTokenizedString ()
Returns the tokenized string.
bool inRange ()
Checks to see if we have reached the end of the range of the input string.
bool isSpecial (char)
Checks if a character is a "special" (parsable) character.
Private Member Functions
bool readCharacter ()
Used to move the peek and index and to increase the Admin column var.
bool readCharacter (char)
Reads a character AND determines if it satisfies a desired value.
Token handleNumber ()
Functions for handling the given types of valid symbols encountered.
Token handleSymbol ()
Function handles symbols read from the source PL program string.
Token handleCharString ()
Handles the scanning duties for a regular character string.
Private Attributes
int src_i
Used in the general parsing of the source file.
char peek
string * source
Eventually refers to a PL source code string.
string tokenizedString
A string of tokenized variables.
vector< string > reservedWords
A vector of reserved words.
SymbolTable * symTable
Pointers to necessary Main objects needed by the Scanner.
Admin * adminPtr
Detailed Description
Scanner object reads chars, constructs tokens and contributes to parser/symboltable.
It uses a collection of switches to handle certain symbols and mediations, but has a swath of functions dedicated to particular handling of certain types of input symbols.
The Scanner keeps track of its Peek and Index locations (relative to the PL source column) and provides a suite of tokenization functions.
Note in Advance: "src" and "source" often refer to the SOURCE File string passed all the way (by reference or pointer) from Main. This is the PL program being loaded.
Constructor & Destructor Documentation
Scanner::Scanner (SymbolTable & table, Admin & admin)
There should only be this one kind of constructor.
Constructs the Scanner object using a symboltable and admin reference.
The scanner is given necessary Symbol Table and Admin class object references, and assigns a class-local pointer to each of them.
Default/beginning values are assigned to the index, the peek variable and the source string ptr.
We insert a predefined list of reserved words into a vector for future use and easy expansion.
Parameters:
table A reference to the Symbol table from the Administrator object.
admin A reference to the Administrator class object in main.
References adminPtr, peek, reservedWords, source, src_i, and symTable.
Scanner::~Scanner () [inline]
Basic, empty destructor.
Member Function Documentation
string Scanner::getTokenizedString ()
Returns the tokenized string.
Returns the tokenized string, in human readable form.
This function is for temporary use and debugging and will be dropped further into the project.
Returns:
std::string
References tokenizedString.
Token Scanner::handleCharString () [private]
Handles the scanning duties for a regular character string.
Creates a string based off of whether the input line (until an atomic terminator) is a valid, full string. A string is valid so long as it starts with an alphabetic character. A valid alpha string can contain numbers and underscores. It finally returns a token of a type determined by the characters read.
Returns:
Token A type of token based on the kind of character symbol found.
Quintessentially, we have a new Token with the String since this one could not be found.
We return a Token of the str, as the token already exists in our table, as a reserved word.
Finally, we know that this symbol was found, and thus exists, so we return it as a token.
References BADNAME, SymbolTable::findLexeme(), IDENTIFIER, SymbolTable::makeEntry(), peek, readCharacter(), and symTable.
Token Scanner::handleNumber () [private]
Functions for handling the given types of valid symbols encountered.
Handles the scanning procedure(s) when we have encountered a digit.
If we encounter a digit, other digits (or symbols) may follow after. Thus, we account for this by peeking at the next [char]acter and converting it to a digit. We add this to a total Integer by a simple base10 method.
The lexeme itself is constructed from the peek chars in their raw form, but only when the numeral is valid. An invalid numeral gets an INVALID lexeme, though we could easily give it a "real" lexeme if preferred.
Returns:
Token A token representing the valid or invalid numeral found.
We peek ahead at the next character, and add it by base10 multiples until the next peek is no longer a digit/numeral.
The numeral becomes a token only if it satisfies our lexicon.
Otherwise, we create an error token and allow it to be handled as appropriate.
References BADNUMERAL, NUMERAL, NUMERAL_LOWER_BOUND, NUMERAL_UPPER_BOUND, peek, readCharacter(), and spellOutTypeName().
Token Scanner::handleSymbol () [private]
Function handles symbols read from the source PL program string.
We create a temporary token and a Type to reflect a symbol that does not match ours. We construct the token based off of the appropriate Type and return it when completed.
Certain symbols require special handling (dual symbols, such as "->") and are accomodated for by peeking for a possible following symbol. If none are found, we reverse the peek and continue.
See also:
token.h
enum Type{};
Returns:
Token A token that represents the symbol we handled.
An '[' symbol can be followed by an ']' symbol.
An '-' symbol can be followed by an '>' symbol.
An ':' symbol can be followed by an '=' symbol.
References AND, ARROW, BADSYMBOL, BOTHSQUAREBRACKETS, COLONEQUALS, COMMA, DIVIDE, EQUALS, FORSLASH, GT, LB, LSB, LT, MINUS, peek, PERIOD, PIPE, PLUS, RB, readCharacter(), RSB, SC, src_i, TILDA, TIMES, and UNKNOWN.
bool Scanner::inRange ()
Checks to see if we have reached the end of the range of the input string.
Checks to see if the Index of the Scanner is within the input PL source file string size.
Essentially, EOF().
See also:
Admin::scan()
Returns:
bool False if we are out of range.
References source, and src_i.
bool Scanner::isSpecial (char ch)
Checks if a character is a "special" (parsable) character.
Checks to see if a given input char is a special character.
If the character is an accepted special character, it will trip one of the following switch cases. Otherwise, it will hit the default case and return false.
Parameters:
ch Input Character to compare.
Returns:
boolean True if it's a special character.
void Scanner::loadSource (string & src)
Links the Scanner's "source" string to the original PL source code File from main.
Load the source into a local string pointer/reference, saving memory and time on larger source files.
If the source file isn't empty, we then kick off our indexes by reading a character for our scanner.
Parameters:
src
References readCharacter(), and source.
Token Scanner::nextToken ()
Goes to the next token and attempts to handle it; otherwise, it grabs the appropriate handler.
Handles the Token reading, mediation and assignment(s).
This function is currently represents the core functionality of the scanner. It mediates input string by choosing the appropriate token handler such as "handleNumber".
Additionally, it makes sure that whitespace, tabs, comments, and newlines are appropriately parsed.
This latter mediation is handled by reading a new character until an appropriate "non-skippable" character/possible token is encountered.
Ultimately, it creates a Token to return to its caller.
Precondition:
A Token is expected, we are at the start of a statement block.
Postcondition:
A Token has been created and the peek/index are at the start of a new statement.
Returns:
Token The next token read from the PL Source File.
This block is used to skip the whitespaces and associated formatting characters such as tab.
We've reached a newline, so the column will now go back to left/'1'. We read this character to check if it's a comment. If it's a comment, we can skip this line and make a Comment token. Otherwise, we construct a Newline token.
Nothing above was found, but it could be a special character within a comment.
But if it's not in a comment, then that means we must handle it.
We've encountered a broken symbol. Increment our index' and return an error token.
An unknown symbol has been encountered. This should almost never happen.
References adminPtr, BADSYMBOL, COMMENT, handleCharString(), handleNumber(), handleSymbol(), isSpecial(), NEWLINE, Admin::newLine(), peek, readCharacter(), Admin::resetColumn(), spellOutTypeName(), and UNKNOWN.
bool Scanner::readCharacter (char c) [private]
Reads a character AND determines if it satisfies a desired value.
Verifies that the next character matches a desired character.
Overload of readch, checks to see if the next peeked character matches the parameter Its prime difference is that the return var is based off of a parameter, rather than off of whether the range end has been reached.
Parameters:
c A character that we expect to find (ie a '>' after a '-')
Returns:
bool A boolean for if the peeked character matches the parameter character.
References peek, and readCharacter().
bool Scanner::readCharacter () [private]
Used to move the peek and index and to increase the Admin column var.
Sets the peek value to the next character if not out of bounds.
Sets our peek to the value at our index (so, the offset is +1) This is one in front of src_i itself. We increase src_i to accomodate the next read and peek.
Returns:
bool A boolean indicating if we're out of range after reading.
References adminPtr, Admin::increaseColumn(), inRange(), peek, source, and src_i.
void Scanner::scan ()
Unused internal Scanning function.
Presently unused/for future use Scan function for the Scanner itelf.
Will be rewritten and used in the future.
This could be called from the Admin or Parser as needed.
Main running function for the scanner, this returns tokens and then concatinates the token to a string for output later.
References inRange(), nextToken(), tokenizedString, and Token::toString().
Member Data Documentation
Admin* Scanner::adminPtr [private]
char Scanner::peek [private]
vector<string> Scanner::reservedWords [private]
A vector of reserved words.
Currently not used, but will be useful later.
string* Scanner::source [private]
Eventually refers to a PL source code string.
int Scanner::src_i [private]
Used in the general parsing of the source file.
SymbolTable* Scanner::symTable [private]
Pointers to necessary Main objects needed by the Scanner.
string Scanner::tokenizedString [private]
A string of tokenized variables.
Currently unused.
The documentation for this class was generated from the following files:
scanner.h
scanner.cpp