CJA-PL-Compiler: First Class Reference
First Class Reference
Essentially, everything done in this program relies upon the Set class.
#include <first.h>
Public Member Functions
First ()
Base Constructor.
Static Public Member Functions
static Set Program ()
The following functions have been chunked according to logical groups, but I avoided re-ordering them at all in case there was a reason for the ordering - such as following closely to the book's production rules or something like that.
static Set Block ()
Returns the First set of Block, which is of "begin".
static Set DefinitionPart ()
Returns the First set of DefinitionPart, which is of Definition.
static Set Definition ()
Returns the FS of Definition, which consists of ConstantDefinition, VariableDefinition and ProcedureDefinition.
static Set ConstantDefinition ()
Returns the First set of ConstantDefinition, which is "const".
static Set VariableDefinition ()
Returns the First set of VariableDefinition, which is that of TypeSymbol.
static Set VariableDefinitionPart ()
Returns the First set of VariableDefinitionPart, which is "array" and that of VariableList.
static Set TypeSymbol ()
Returns the First set of TypeSymbol, which is "integer" and "boolean".
static Set VariableList ()
Returns the First set of VariableList, which is that of VariableName.
static Set ProcedureDefinition ()
Returns the First set of ProcedureDefinition, which is "proc".
static Set StatementPart ()
Returns the First set of StatementPart, which is of Statement.
static Set Statement ()
Returns the First set of Statement, which consists of that of EmptyStatement, ReadStatement, WriteStatement, AssignmentStatement, ProcedureStatement, IfStatement and DoStatement.
static Set EmptyStatement ()
Returns the First set of EmptyStatement, which is "skip".
static Set ReadStatement ()
Returns the First set of ReadStatement, which is "read".
static Set VariableAccessList ()
Returns the First set of VariableAccessList, which is that of VariableAccess.
static Set WriteStatement ()
Returns the First set of WriteStatement, which is "write".
static Set ExpressionList ()
Returns the First set of ExpressionList, which is that of Expression.
static Set AssignmentStatement ()
Returns the First set of AssignmentStatement, which is that of VariableAccessList.
static Set ProcedureStatement ()
Returns the First set of ProcedureStatement, which is "call".
static Set IfStatement ()
Returns the First set of IfStatement, which is "if".
static Set DoStatement ()
Returns the First set of DoStatement, which is of "do".
static Set GuardedCommandList ()
Returns the First set of GuardedCommandList, which is of GuardedCommand.
static Set GuardedCommand ()
Returns the First set of GuardedCommand, which is of Expression.
static Set Expression ()
Returns the First set of Expression, which is that of PrimaryExpression.
static Set PrimaryOperator ()
Returns the First set of PrimaryOperator, which is "&" and "|".
static Set PrimaryExpression ()
Returns the First set of PrimaryExpression, which is that of SimpleExpression.
static Set RelationalOperator ()
Returns the First set of RelationalOperator, which is "<", ">" and "=".
static Set SimpleExpression ()
Returns the First set of SimpleExpression, which is "-" and that of Term.
static Set AddingOperator ()
Returns the First set of AddingOperator, which is "+" and "-".
static Set Term ()
Returns the First set of Term, which is that of Factor.
static Set MultiplyingOperator ()
Returns the First set of MultiplyOperator, which is "*", "\" and "/".
static Set Factor ()
Returns the First set of Factor, which is "(", "~" and that of VariableAccess and Constant.
static Set VariableAccess ()
Returns the First set of VariableAccess, which is that of VariableName and IndexedSelector.
static Set IndexedSelector ()
Returns the First set of IndexedSelector, which is "[".
static Set Constant ()
Returns the First set of Constant, which is that of BooleanSymbol and ConstantName.
static Set Numeral ()
Returns the First set of Numeral, which is "num".
static Set BooleanSymbol ()
Returns the First set of BooleanSymbol, which is "true" and "false".
static Set ConstantName ()
Returns the First set of ConstantName, which is "name".
static Set VariableName ()
Returns the First set of VariableName, which is "name".
static Set ProcedureName ()
Returns the First set of ProcedureName, which is "name".
static Set FactorName ()
Returns the First set of FactorName, which is "name".
Detailed Description
Essentially, everything done in this program relies upon the Set class.
A static class that constructs First Sets for given productions/nonterminals. Please refer to the specification for a FIRST SET as well as the PL Language.
The First object provides a series of static functions that return the semi-predefined FIRST sets for any given production rule in the PL language.
These sets are composed using the appropriate set of nonterminals and their first sets, and to that end, their terminals/nonterminals.
As such, the functionality of virtually every function in this object is the same, but with tweaked heuristics and unique Set string values per each set.
Constructor & Destructor Documentation
First::First ()
Base Constructor.
Base constructor for the first class.
Member Function Documentation
Set First::AddingOperator () [static]
Returns the First set of AddingOperator, which is "+" and "-".
Set First::AssignmentStatement () [static]
Returns the First set of AssignmentStatement, which is that of VariableAccessList.
References VariableAccessList().
Set First::Block () [static]
Returns the First set of Block, which is of "begin".
Set First::BooleanSymbol () [static]
Returns the First set of BooleanSymbol, which is "true" and "false".
Set First::Constant () [static]
Returns the First set of Constant, which is that of BooleanSymbol and ConstantName.
References BooleanSymbol(), ConstantName(), Set::munion(), and Numeral().
Set First::ConstantDefinition () [static]
Returns the First set of ConstantDefinition, which is "const".
Set First::ConstantName () [static]
Returns the First set of ConstantName, which is "name".
Set First::Definition () [static]
Returns the FS of Definition, which consists of ConstantDefinition, VariableDefinition and ProcedureDefinition.
References ConstantDefinition(), Set::munion(), ProcedureDefinition(), and VariableDefinition().
Set First::DefinitionPart () [static]
Returns the First set of DefinitionPart, which is of Definition.
References Definition().
Set First::DoStatement () [static]
Returns the First set of DoStatement, which is of "do".
Set First::EmptyStatement () [static]
Returns the First set of EmptyStatement, which is "skip".
Set First::Expression () [static]
Returns the First set of Expression, which is that of PrimaryExpression.
References PrimaryExpression().
Set First::ExpressionList () [static]
Returns the First set of ExpressionList, which is that of Expression.
References Expression().
Set First::Factor () [static]
Returns the First set of Factor, which is "(", "~" and that of VariableAccess and Constant.
References Constant(), and VariableAccess().
Set First::FactorName () [static]
Returns the First set of FactorName, which is "name".
Set First::GuardedCommand () [static]
Returns the First set of GuardedCommand, which is of Expression.
References Expression().
Set First::GuardedCommandList () [static]
Returns the First set of GuardedCommandList, which is of GuardedCommand.
References GuardedCommand().
Set First::IfStatement () [static]
Returns the First set of IfStatement, which is "if".
Set First::IndexedSelector () [static]
Returns the First set of IndexedSelector, which is "[".
Set First::MultiplyingOperator () [static]
Returns the First set of MultiplyOperator, which is "*", "\" and "/".
Set First::Numeral () [static]
Returns the First set of Numeral, which is "num".
Set First::PrimaryExpression () [static]
Returns the First set of PrimaryExpression, which is that of SimpleExpression.
References SimpleExpression().
Set First::PrimaryOperator () [static]
Returns the First set of PrimaryOperator, which is "&" and "|".
Set First::ProcedureDefinition () [static]
Returns the First set of ProcedureDefinition, which is "proc".
Set First::ProcedureName () [static]
Returns the First set of ProcedureName, which is "name".
Set First::ProcedureStatement () [static]
Returns the First set of ProcedureStatement, which is "call".
Set First::Program () [static]
The following functions have been chunked according to logical groups, but I avoided re-ordering them at all in case there was a reason for the ordering - such as following closely to the book's production rules or something like that.
For each of the following functions, a base set or sets are created with the appropriate set values corresponding to the First set for the given nonterminal that each function represents (by name). After this, sets are created using the mUnion of the given function set with the following productions' first sets.
Finally, the static functions return the given sets and are accessible without the class being instantiated.
In other words, every function here is representative of a Function in the Parser, and delivers their Follow sets upon call.
For each of the following functions, a base set or sets are created with the appropriate set values corresponding to the First set for the given nonterminal that each function represents (by name). After this, sets are created using the mUnion of the given function set with the following productions' first sets.
Finally, the static functions return the given sets and are accessible without the class being instantiated.
In other words, every function here is representative of a Function in the Parser, and delivers their Follow sets upon call. Returns the First set of Program, which is of Block.
References Block().
Set First::ReadStatement () [static]
Returns the First set of ReadStatement, which is "read".
Set First::RelationalOperator () [static]
Returns the First set of RelationalOperator, which is "<", ">" and "=".
Set First::SimpleExpression () [static]
Returns the First set of SimpleExpression, which is "-" and that of Term.
References Term().
Set First::Statement () [static]
Returns the First set of Statement, which consists of that of EmptyStatement, ReadStatement, WriteStatement, AssignmentStatement, ProcedureStatement, IfStatement and DoStatement.
References AssignmentStatement(), DoStatement(), EmptyStatement(), IfStatement(), Set::munion(), ProcedureStatement(), ReadStatement(), and WriteStatement().
Set First::StatementPart () [static]
Returns the First set of StatementPart, which is of Statement.
References Statement().
Set First::Term () [static]
Returns the First set of Term, which is that of Factor.
References Factor().
Set First::TypeSymbol () [static]
Returns the First set of TypeSymbol, which is "integer" and "boolean".
Set First::VariableAccess () [static]
Returns the First set of VariableAccess, which is that of VariableName and IndexedSelector.
References IndexedSelector(), Set::munion(), and VariableName().
Set First::VariableAccessList () [static]
Returns the First set of VariableAccessList, which is that of VariableAccess.
References VariableAccess().
Set First::VariableDefinition () [static]
Returns the First set of VariableDefinition, which is that of TypeSymbol.
References TypeSymbol().
Set First::VariableDefinitionPart () [static]
Returns the First set of VariableDefinitionPart, which is "array" and that of VariableList.
References VariableList().
Set First::VariableList () [static]
Returns the First set of VariableList, which is that of VariableName.
References VariableName().
Set First::VariableName () [static]
Returns the First set of VariableName, which is "name".
Set First::WriteStatement () [static]
Returns the First set of WriteStatement, which is "write".
The documentation for this class was generated from the following files:
first.h
first.cpp