CJA-PL-Compiler: Admin Class Reference
Admin Class Reference
This is the main administrator class that manages the different compiler functions.
#include <admin.h>
Public Member Functions
Admin (string &, int debug)
Base constructor for the Administrator.
void recordError (string)
Records the Error Message string into the Error vector.
int scan ()
Executes the scanner function and returns an integer count of the errors found.
Token nextToken ()
The primary tokenizing function that can be called for scanning and parsing.
void newLine ()
A newline operation is performed as our current line is valid.
void increaseColumn ()
Our column count management functions allow us to report exact error locations.
void resetColumn ()
The default "left-aligned" column is 1, we reset it when we reach the end of a line.
bool checkMaxErrors ()
Checks if we have reached the maximum number of errors.
int getColumnNumber ()
Basic retrieval functions, used for debug.
int getLineNumber ()
Send back the line number without edits.
void emit1 (string)
Our functions for emitting our ASM code.
void emit2 (string, int)
Double Emit Function Outputs two-param interp code.
void emit3 (string, int, int)
Trinary Emit Function Outputs three-piece code.
string getASM ()
Returns our stringstream code to be used by the assembler.
int getErrorCount ()
Returns an error count,.
Public Attributes
int column
int asmDebugFlag
Determines whether the EMITS output or not.
Private Attributes
std::vector< string > error_msgs
Vectors used to store error details.
std::vector< int > error_line
int current_line
We track the current line and column locations while reading through our File string.
stringstream error_str
We store our errors in a StringStream for easy manipulation and conversion.
stringstream assemblerStream
We store our Intermediary/Back-End code in a StringStream for eventual writing to file or output.
SymbolTable * table
Symbol Table, Parser and Scanner object pointers.
Scanner * scanner
Parser * parser
int symTIndex
The Index integer for our symbol table.
bool correctLine
If a line cannot be scanned/parsed, this boolean is used to indicate such.
int errorCount
Simple tracking of the number of errors encountered.
bool tokenFlag
Flag used to turn off/on token found printouts.
Detailed Description
This is the main administrator class that manages the different compiler functions.
This class mediates between the different analytical portions of the compiler. The Administrator class ensures that the Scanner and Parser communicate using the same set of data, such as the same Symbol Table(s), same line/column count, and the same error data.
As of now, the Administrator executes the scanning and parsing functions when needed and supplies the correct data for each. It may also mediate for the Error Handling classes.
Constructor & Destructor Documentation
Admin::Admin (string & src, int DEBUG)
Base constructor for the Administrator.
Constructor for the Admin class.
The constructor takes in the finalized File string object pointer from the Main file.
Parameters:
src variable
Sets the default values of our class variables, then creates the symbol table and scanner.
Uses the source string "src", which is the File string reference containing the entire PL program.
Parameters:
src The PL program in the File string.
correctLine could technically be used a constructor sentinel in the future.
We send the symbol table to the Scanner, along with a reference to the Administrator.
The reference to the "File" string is sent to the scanner.
Create the base Parser object with a pointer back to here to allow it to access the scanner->
A flag for managing the output of TOKEN debug information. Set to TRUE to see said information.
References asmDebugFlag, column, correctLine, current_line, errorCount, Scanner::loadSource(), parser, scanner, symTIndex, table, and tokenFlag.
Member Function Documentation
bool Admin::checkMaxErrors ()
Checks if we have reached the maximum number of errors.
If we have reached the maximum number of errors, we return a true statement as well as letting the operator/user know this has happened. Used to shorten code above.
Returns:
A boolean indicating if we have too many errors.
References errorCount, and MAXERRORS.
void Admin::emit1 (string str)
Our functions for emitting our ASM code.
Singular Emit Function Outputs the single string param of backend code.
Stores in primary backend StringStream.
References asmDebugFlag, and assemblerStream.
void Admin::emit2 (string str, int i)
Double Emit Function Outputs two-param interp code.
Stores in primary backend StringStream.
References asmDebugFlag, and assemblerStream.
void Admin::emit3 (string str, int i, int j)
Trinary Emit Function Outputs three-piece code.
Stores in primary backend StringStream.
References asmDebugFlag, and assemblerStream.
string Admin::getASM ()
Returns our stringstream code to be used by the assembler.
Returns the Assembler stream.
References assemblerStream.
int Admin::getColumnNumber ()
Basic retrieval functions, used for debug.
Retrieve the Column number in raw/unchanged/unmodified form.
References column.
int Admin::getErrorCount ()
Returns an error count,.
Returns the Error count as an int.
References errorCount.
int Admin::getLineNumber ()
Send back the line number without edits.
References current_line.
void Admin::increaseColumn ()
Our column count management functions allow us to report exact error locations.
Our column count is increased.
We use it to track error and token positions.
References column.
void Admin::newLine ()
A newline operation is performed as our current line is valid.
Used to adjust the current line, and also for skipping lines (errors, comments, etc.
See also:
formal Definition of newLine()
)
References correctLine, and current_line.
Token Admin::nextToken ()
The primary tokenizing function that can be called for scanning and parsing.
Primary tokenizing management function as used by the Admin to construct and retrieve tokens.
This function receives a Token from the scanner and handles errors/exceptions at the same time. It is called for Scanning and Parsing, respectively.
Precondition:
The scanner is at a specific index i
Postcondition:
The index and lookahead are at i+1 and i+2 and a token has been constructed.
Returns:
A specific token as pertains to the given type from the scanner
We check if the current token is an error token, and report it to the user. At the moment, the program only reports one error per line. The code is boilerplate for the rest of these, so they could be a switch statement.
This outputs the Token to the Screen in a < ___,___,___> format.
References BADNAME, BADNUMERAL, BADSYMBOL, checkMaxErrors(), column, current_line, ENDOFFILE, error_str, errorCount, Token::getLexeme(), Token::getType(), Scanner::inRange(), Scanner::nextToken(), recordError(), scanner, tokenFlag, and Token::toString().
void Admin::recordError (string msg)
Records the Error Message string into the Error vector.
Function outputs the error and adjusts vars proceedingly.
recordError is passed a string describing a recorded error that has occured.
The function adjusts internal values accordingly, and outputs the given message to the screen. As of now, only one error per line is recorded, then we dump the line.
Parameters:
msg The error message to be recorded.
References correctLine, error_msgs, and error_str.
void Admin::resetColumn ()
The default "left-aligned" column is 1, we reset it when we reach the end of a line.
References column.
int Admin::scan ()
Executes the scanner function and returns an integer count of the errors found.
The Admin function that operates the Scanner and details errors as necessary.
We check for the various heuristics of the scanner, and then start the Parser. The parser itself then has direct control fo the scanner, though this function ensures that the scanner or parser's error thresholds are accounted for.
We output the token, and ensure that we stay within "file" range (string, technically).
Finally, we return an integer that counts the number of errors. Thus, if a 0 means our scanner has scanned successfully and the parser has not failed.
Precondition:
We have a file string of a PL program and an empty symbol table.
Postcondition:
We will have a complete symbol table and have scanned our PL file. Our file will be parsed.
Returns:
An integer count of errors encountered.
Run the Parser! The parser itself will also manage the error count.
We return an "all clear" digit of 0 if there were no errors. The rest is handled in the main.
We output to an ASM file.
References assemblerStream, error_msgs, errorCount, Parser::existsError(), Scanner::inRange(), parser, Parser::run(), and scanner.
Member Data Documentation
int Admin::asmDebugFlag
Determines whether the EMITS output or not.
stringstream Admin::assemblerStream [private]
We store our Intermediary/Back-End code in a StringStream for eventual writing to file or output.
int Admin::column
bool Admin::correctLine [private]
If a line cannot be scanned/parsed, this boolean is used to indicate such.
int Admin::current_line [private]
We track the current line and column locations while reading through our File string.
std::vector<int> Admin::error_line [private]
std::vector<string> Admin::error_msgs [private]
Vectors used to store error details.
We store any strings of error messages that may occur, and where they occur.
stringstream Admin::error_str [private]
We store our errors in a StringStream for easy manipulation and conversion.
int Admin::errorCount [private]
Simple tracking of the number of errors encountered.
We abandon compilatiuon if this matches or exceeds the MAXERRORS definition.
See also:
MAXERRORS
Parser* Admin::parser [private]
Scanner* Admin::scanner [private]
int Admin::symTIndex [private]
The Index integer for our symbol table.
Increases per entry, removing the need to use the Symbol Table's iterator functions.
SymbolTable* Admin::table [private]
Symbol Table, Parser and Scanner object pointers.
This allows us to send symbol tables and scanners to and from other objects, and makes it easier to manage memory and overflows.
bool Admin::tokenFlag [private]
Flag used to turn off/on token found printouts.
The documentation for this class was generated from the following files:
admin.h
admin.cpp