CJA-PL-Compiler: BlockTable Class Reference
BlockTable Class Reference
The structure facilitating the creation and manipulation of Program Blocks.
#include <blocktable.h>
Public Member Functions
BlockTable (SymbolTable &)
Specification File.
~BlockTable ()
bool search (int lookFor)
Checks if a given TableEntry ID is found in the current Block.
bool search (int lookFor, TableEntry &entry)
Locates a given ID in the current Block, then links said entry to the input TableEntry reference.
bool search (int, int &)
Locates a given TE ID in the current Block, and pairs its index with the input integer reference.
bool define (int newid, Kind newkind, mType newtype, int newsize, int newvalue, int startLabel)
bool define (int newid, Kind newkind, mType newtype, int newsize, int newvalue)
Creates an object if we don't find it in the current block.
bool define (int newid, Kind newkind, mType newtype)
Defines a new block entry, but for non-const/non-array types.
bool redefineSize (int, int)
Redefines the size of an Array entry in the current block, if it is found, otherwise returns false.
TableEntry find (int lookfor, bool &error)
Searches through all of the blocks for a corresponding tableEntry and returns it.
bool newBlock ()
Push our old block onto the Table and create a new one for the new scope.
bool endBlock ()
Decreaments the current block index, pops a block off the block table, and replaces the currentBlock with the previous one.
void printBlock (vector< TableEntry * >)
Prints the passed-in Block (tableentry vector) in a tabular format.
void printBlock (vector< TableEntry * >, string)
Prints all of the table entries in the passed-in block, but with a manual heading.
void printAllBlocks ()
Prints all of the Block data in our Blocks vector using the above methods.
string convertKind (int)
Returns a string representation of a Kind enum.
string convertType (int)
Returns a string representation of a Type enum.
string tableEntrytoString (TableEntry)
Returns a string representation of a Table Entry.
vector< TableEntry * > returnCurrentBlock ()
Returns the current block (TableEntry* vector).
vector< vector< TableEntry * > > returnAllBlocks ()
Returns every block except the current one, since it is directly accessible.
int currentLevel ()
Returns the current block level.
string returnLexeme (int)
Returns a given lexeme as a string.
Public Attributes
SymbolTable * table
Empty pointer, which has a Scanner's Symbol Table attached when this class is Constructed.
Private Attributes
vector< vector< TableEntry * > > blocks
A vector of Blocks.
vector< TableEntry * > currentBlock
The current scope/block.
int currentBlockIndex
Counter that keeps track of our current nested level/the number of blocks within the vector.
Detailed Description
The structure facilitating the creation and manipulation of Program Blocks.
The BlockTable data structure allows us to keep track of Program Blocks, through a vector of such objects. A block itself is a Vector of TableEntry structures, and represents a logical block in a PL program, defined by a Begin/End pair such as a procedure call.
The blocktable provides the capabilities and capacities for adding new blocks, searching for entries in given blocks, adding entries to blocks and smartly allowing us to construct these TableEntry structures through limited and properly defined access to the core compiler's Symbol Table.
Constructor & Destructor Documentation
BlockTable::BlockTable (SymbolTable & symbolTable)
Specification File.
Base Constructor.
A BlockTable can only be constructed if a Scanner, and thus a SymbolTable, exist. We assign the address of the symbol table to our local pointer, and set the base index of our block level/scope for the table/program.
References currentBlockIndex, and table.
BlockTable::~BlockTable ()
Member Function Documentation
string BlockTable::convertKind (int kind)
Returns a string representation of a Kind enum.
Returns a given Kind of a TableEntry in string format.
Converts a given Kind enum into a corresponding string. Mostly for error checking. If a given kind is not found, we report this.
References ARRAY, CONSTANT, DEFINED, PROCEDURE, and VARIABLE.
string BlockTable::convertType (int type)
Returns a string representation of a Type enum.
Returns a string representation of a given Type enum, or returns an error message and the function name.
References BOOLEAN, INTEGER, and UNIVERSAL.
int BlockTable::currentLevel ()
Returns the current block level.
Returns the level of the current block, i.e.
the index and scope.
References currentBlockIndex.
bool BlockTable::define (int newid, Kind newkind, mType newtype)
Defines a new block entry, but for non-const/non-array types.
Defines a new entry in the current block table if not found.
Defines a new TableEntry record using the input data, adds it to the current block's vector of TableEntries, and returns true.
If the item ALREADY existed (i.e. we try to define X when X is already found) then it returns false.
This version of the function differs in that it is used for all non-const and non-array types.
References define().
bool BlockTable::define (int newid, Kind newkind, mType newtype, int newsize, int newvalue)
Creates an object if we don't find it in the current block.
Defines a new entry in the current block table if not found.
We don't call Find as the caller of Define will know whether to check the other blocks. Return true when the object is stored successfully. returns false if the current block contains the object already
Defines a new TableEntry record using the input data, adds it to the current block's vector of TableEntries, and returns true.
If the item ALREADY existed (i.e. we try to define X when X is already found) then it returns false.
newsize and newvalue are used to define const/array sizes/values, which need special handling. If the object is not a const or array, it will get a 0 for each.
References define().
bool BlockTable::define (int newid, Kind newkind, mType newtype, int newsize, int newvalue, int startLabel)
References currentBlock, currentBlockIndex, TableEntry::displacement, TableEntry::id, TableEntry::level, TableEntry::okind, TableEntry::otype, search(), TableEntry::size, TableEntry::startLabel, and TableEntry::value.
bool BlockTable::endBlock ()
Decreaments the current block index, pops a block off the block table, and replaces the currentBlock with the previous one.
Ends the current block/exits the top-most scope.
We clear the current block information, which is synonymous logically with ending the current given scope.
All of the current tableEntrys go out of scope, and are thus cleared along with the other block data.
Additionally, we move the previous block data back into our temporary block, and remove it from the top of the Blocks vector. This brings the BlockTable to the state it was in before it last raised its scope.
References blocks, currentBlock, and currentBlockIndex.
TableEntry BlockTable::find (int lookfor, bool & error)
Searches through all of the blocks for a corresponding tableEntry and returns it.
Searches this and all above blocks for a given TableEntry ID.
Otherwise, it returns a blank entry and an activated (TRUE) error flag by reference.
Searches for a given TableEntry by ID in all of the blocks above and including the current one. This essentially searches all entries within scope to see if one currently exists.
If an entry is found, we pass back an "all ok" flag (error = false) and directly return a copy of the given tableEntry itself.
Otherwise, we return a blank table entry and activate our error flag (if the item is not found).
References blocks, and currentBlock.
bool BlockTable::newBlock ()
Push our old block onto the Table and create a new one for the new scope.
Adds a new block to the BlockTable and pushes the old one onto the main vector.
Returns true-success/false-failure.
If our maximum scope-level has not been reached, then we put the current block onto the overall "previous" vector (i.e. "higher level" of the scope).
Really, we push a copy of it, and clear the current one, which allows us to save on memory and reduce the risk of errors.
As usual, a True is returned if a block could be successfully created, and a false otherwise.
References blocks, currentBlock, currentBlockIndex, and MAXBLOCK.
void BlockTable::printAllBlocks ()
Prints all of the Block data in our Blocks vector using the above methods.
Prints every Block in the BlockTable.
Uses our above helper functions to print out all of the Blocks in our vector and then prints the current block.
References blocks, currentBlock, and printBlock().
void BlockTable::printBlock (vector< TableEntry * > block, string name)
Prints all of the table entries in the passed-in block, but with a manual heading.
Helper Printer function, prints a block's information in an easy-to-read format.
Prints all of the table-entry records in a given passed-in block. A name parameter allows the caller to specificy specifics, such as the current Parser function they are calling from.
It utilizes our tableEntrytoString function to print the individual TableEntry records.
References tableEntrytoString().
void BlockTable::printBlock (vector< TableEntry * > block)
Prints the passed-in Block (tableentry vector) in a tabular format.
Prints out the current block with a "stock" title/heading.
Calls our main Block printing function with a default title of "Block"
bool BlockTable::redefineSize (int id, int newsize)
Redefines the size of an Array entry in the current block, if it is found, otherwise returns false.
Changes the Size of an entry if said Array is found.
Searches the current block for a given Array entry by id. If found, use the index to change its size, and return true. Otherwise (if not found) return false.
References currentBlock, and search().
vector< vector< TableEntry * > > BlockTable::returnAllBlocks ()
Returns every block except the current one, since it is directly accessible.
Returns all of the Blocks.
Returns the Vector of the Blocks, a Vector of a Vector of TableEntry records. Does not return the current block.
References blocks.
vector< TableEntry * > BlockTable::returnCurrentBlock ()
Returns the current block (TableEntry* vector).
Returns the current block.
Returns the current block, a vector of TableEntry pointers.
References currentBlock.
string BlockTable::returnLexeme (int entryID)
Returns a given lexeme as a string.
Grabs the lexeme of a given table ID.
References SymbolTable::getAttributeWhere(), and table.
bool BlockTable::search (int lookFor, int & returnIndex)
Locates a given TE ID in the current Block, and pairs its index with the input integer reference.
Searches for a given entry and also returns its index.
Determines (boolean) if a given lookfor (TE ID) is in the current block. If not, it returns a false. If it is found, it will return true as well as attaching the given Block index (location of the item) to the integer reference.
References currentBlock.
bool BlockTable::search (int lookFor, TableEntry & entry)
Locates a given ID in the current Block, then links said entry to the input TableEntry reference.
Search function with ID and actual Entry returns.
Checks all of the entries in the current block to see if the entry ID is found. If found, we return true, but also attach the given item's address to the passed-in reference parameter. Thus, we return a reference to the item as well as the TableEntry ID.
References currentBlock.
bool BlockTable::search (int lookFor)
Checks if a given TableEntry ID is found in the current Block.
Simple search function.
See also:
find()
The user does not need the reference, but just a confirmation that a given TableEntry ID exists in our BlockTable.
The TableEntry refrence is discarded automatically.
Parameters:
lookfor
Returns:
bool a boolean of if the ID was found
string BlockTable::tableEntrytoString (TableEntry entry)
Returns a string representation of a Table Entry.
Converts a given TableEntry record to a String record type.
Creates a string with a specific formatting for outputting the given information of a specific Table Entry record.
References convertKind(), convertType(), SymbolTable::getAttributeWhere(), TableEntry::id, TableEntry::okind, TableEntry::otype, TableEntry::size, table, and TableEntry::value.
Member Data Documentation
vector< vector<TableEntry* > > BlockTable::blocks [private]
A vector of Blocks.
This represents a "table" of records, since a Block is a vector of table entries.
vector<TableEntry*> BlockTable::currentBlock [private]
The current scope/block.
All operations are done on this block. When we enter a new/deeper Scope, we push this block onto our main vector. Likewise, when the current scope dies, we do the inverse, and refill this block.
int BlockTable::currentBlockIndex [private]
Counter that keeps track of our current nested level/the number of blocks within the vector.
SymbolTable* BlockTable::table
Empty pointer, which has a Scanner's Symbol Table attached when this class is Constructed.
The documentation for this class was generated from the following files:
blocktable.h
blocktable.cpp