CJA-PL-Compiler: Interpreter Class Reference
Interpreter Class Reference
#include <interp.h>
Public Member Functions
Interpreter (string, bool=false)
void memory_dump (string) const
Private Member Functions
void load_program (string)
void run_program ()
void runtime_error (string, int=-1)
void allocate (int)
void variable (int, int)
void index (int, int)
void constant (int)
void value ()
void plnot ()
void multiply ()
void divide ()
void modulo ()
void minus ()
void add ()
void subtract ()
void less ()
void equal ()
void greater ()
void pland ()
void plor ()
void read (int)
void write (int)
void assign (int)
void call (int, int)
void arrow (int)
void bar (int)
void fi (int)
void proc (int, int)
void endproc ()
void prog (int, int)
void endprog ()
Private Attributes
int store [STORE_SIZE+1]
int stack_bottom
int stack_register
int base_register
int program_register
bool running
bool stepping
Constructor & Destructor Documentation
Interpreter::Interpreter (string filename, bool step = false)
References load_program(), run_program(), and stepping.
Member Function Documentation
void Interpreter::add () [private]
References program_register, stack_register, and store.
void Interpreter::allocate (int words) [private]
References runtime_error(), stack_register, and STORE_SIZE.
void Interpreter::arrow (int address) [private]
References program_register, stack_register, and store.
void Interpreter::assign (int count) [private]
References program_register, stack_register, and store.
void Interpreter::bar (int address) [private]
References program_register.
void Interpreter::call (int level, int address) [private]
References allocate(), base_register, program_register, stack_register, and store.
void Interpreter::constant (int value) [private]
References allocate(), program_register, stack_register, and store.
void Interpreter::divide () [private]
References program_register, stack_register, and store.
void Interpreter::endproc () [private]
References base_register, program_register, stack_register, and store.
void Interpreter::endprog () [private]
References running.
void Interpreter::equal () [private]
References program_register, stack_register, and store.
void Interpreter::fi (int line_number) [private]
References runtime_error().
void Interpreter::greater () [private]
References program_register, stack_register, and store.
void Interpreter::index (int bound, int line_number) [private]
References program_register, runtime_error(), stack_register, and store.
void Interpreter::less () [private]
References program_register, stack_register, and store.
void Interpreter::load_program (string name) [private]
References stack_bottom, store, and STORE_SIZE.
void Interpreter::memory_dump (string name) const
References store, and STORE_SIZE.
void Interpreter::minus () [private]
References program_register, stack_register, and store.
void Interpreter::modulo () [private]
References program_register, stack_register, and store.
void Interpreter::multiply () [private]
References program_register, stack_register, and store.
void Interpreter::pland () [private]
References program_register, stack_register, and store.
void Interpreter::plnot () [private]
References program_register, stack_register, and store.
void Interpreter::plor () [private]
References program_register, stack_register, and store.
void Interpreter::proc (int variable_length, int address) [private]
References allocate(), and program_register.
void Interpreter::prog (int variable_length, int address) [private]
References allocate(), base_register, program_register, stack_bottom, and stack_register.
void Interpreter::read (int count) [private]
References program_register, stack_register, and store.
void Interpreter::run_program () [private]
References add(), arrow(), assign(), bar(), call(), constant(), divide(), endproc(), endprog(), equal(), fi(), greater(), index(), less(), minus(), modulo(), multiply(), OP_ADD, OP_AND, OP_ARROW, OP_ASSIGN, OP_BAR, OP_CALL, OP_CONSTANT, OP_DIVIDE, OP_ENDPROC, OP_ENDPROG, OP_EQUAL, OP_FI, OP_GREATER, OP_INDEX, OP_LESS, OP_MINUS, OP_MODULO, OP_MULTIPLY, OP_NOT, OP_OR, OP_PROC, OP_PROG, OP_READ, OP_SUBTRACT, OP_VALUE, OP_VARIABLE, OP_WRITE, opcode_name, pland(), plnot(), plor(), proc(), prog(), program_register, read(), running, runtime_error(), stepping, store, subtract(), value(), variable(), and write().
void Interpreter::runtime_error (string message, int line_number = -1) [private]
References running.
void Interpreter::subtract () [private]
References program_register, stack_register, and store.
void Interpreter::value () [private]
References program_register, stack_register, and store.
void Interpreter::variable (int level, int displacement) [private]
References allocate(), base_register, program_register, stack_register, and store.
void Interpreter::write (int count) [private]
References program_register, stack_register, and store.
Member Data Documentation
int Interpreter::base_register [private]
int Interpreter::program_register [private]
bool Interpreter::running [private]
int Interpreter::stack_bottom [private]
int Interpreter::stack_register [private]
bool Interpreter::stepping [private]
int Interpreter::store[STORE_SIZE+1] [private]
The documentation for this class was generated from the following files:
interp.h
interp.cpp