CJA-PL-Compiler: Set Class Reference
Set Class Reference
The set class manages logical sets of lexemetic values.
#include <set.h>
Public Member Functions
Set ()
Base constructor.
Set (string)
String constructor that creates a set using the passed Lexeme.
Set (vector< string >)
A constructor that creates a Set out of a complete vector of strings, ie a semi-set.
void add (string)
Appends the given String to the end of the Set vector.
Set remove (string)
Searches for and removes a given String/lexeme from the Set if present, returning the resultant set.
Set munion (Set)
Returns the union of this set with another without actually modifying this set.
vector< string > returnVec ()
Returns the internal Vector of the set, ie the vector representation of the Set object.
string toString ()
Returns a logical String representation of the Set for OUTPUT/user preview/debug purposes only.
bool isMember (string)
Checks to see if a given lexeme is in the Set.
int indexAt (string)
Returns the exact location, within the set, of a given lexeme/input string.
Private Attributes
vector< string > set
The core Set vector of strings itself, whose representation should never be seen.
Detailed Description
The set class manages logical sets of lexemetic values.
A SET is an object containing a vector of lexemic strings.
An overarching Set stopset "sts" is "passed" between nonterminal functions and their productions and is used to mediate the Matching; Said stop set contains the valid values for continuing to parse, and a lack of a specific value within it indicates a syntax error.
The set object uses a Vector of strings to store lexemes. The class also provides core functionality (altering, merging, accessing and viewing the set) in a memory-efficient fashion.
Constructor & Destructor Documentation
Set::Set ()
Base constructor.
Base Constructor.
Set::Set (string str)
String constructor that creates a set using the passed Lexeme.
String constructor, adds the given parameter to the set on construction.
Parameters:
str A lexeme to be added to the Set.
Set::Set (vector< string > vec)
A constructor that creates a Set out of a complete vector of strings, ie a semi-set.
Vector constructor of the Set.
Creates the set using a Vector by straight assignment.
Parameters:
vec A string of lexemes/an unwrapped set.
Member Function Documentation
void Set::add (string str)
Appends the given String to the end of the Set vector.
Adds an input string to the Set object.
Parameters:
str A string lexeme to be added to the Set.
int Set::indexAt (string str)
Returns the exact location, within the set, of a given lexeme/input string.
Finds the exact location of a given string within the Set and returns its index.
We loop through the Set and return the index of the given string. If it is not found, we return -1.
Parameters:
str String representing the parameter whose index we search for.
bool Set::isMember (string str)
Checks to see if a given lexeme is in the Set.
Checks to see if a given string is a member of the set.
We loop through the Set indices to determine if a given lexeme is present.
Parameters:
str String representing the lexeme we are searching for.
Set Set::munion (Set second_set)
Returns the union of this set with another without actually modifying this set.
Appends an input set to this one and returns the resultant set.
A couple of temporary sets are used to perform the Vector modifications, then the temporary set is returned. This set is *not* modified. This is a function to return a proposed Union set, not to actually union two sets. This is done to maintain set integrity between nonterminal nodes.
Parameters:
second_set A set to be appended to the caller set.
temporary sets to ensure original set integrity.
Iteraten through the input set and add any unique values to the temp set.
Return the set union to caller.
References returnVec(), and Set().
Set Set::remove (string str)
Searches for and removes a given String/lexeme from the Set if present, returning the resultant set.
Remove function that Returns a copy of this set with element str removed.
We use temporary sets and check for the existance of a string, then remove it from the temp set and return it.
If the string is not found, we return this original set.
Parameters:
str String representing the lexeme to be "removed" from the return set.
References indexAt().
vector< string > Set::returnVec ()
Returns the internal Vector of the set, ie the vector representation of the Set object.
Returns the core set as a Vector with no wrappings.
Returns:
this set in vector form.
string Set::toString ()
Returns a logical String representation of the Set for OUTPUT/user preview/debug purposes only.
Outputs the Set in basic set-builder-light notation.
Constructs a string from the Vector, adding symbols such as { and commas.
Returns:
a string representation of the set.
Loop through the set and add commas, etc.
Member Data Documentation
vector<string> Set::set [private]
The core Set vector of strings itself, whose representation should never be seen.
The documentation for this class was generated from the following files:
set.h
set.cpp