CJA-PL-Compiler: main.cpp File Reference
main.cpp File Reference
The main "runner" file for the overall Compiler Project.
#include <string>
#include <ctype.h>
#include <iostream>
#include <fstream>
#include <istream>
#include <ostream>
#include <cstring>
#include "admin.h"
#include "token.h"
#include "assembler.h"
#include "interp.h"
Functions
void runAssembler (Admin *admin)
Function prototypes.
void runInterpreter (bool step)
Main function to run our Interpreter.
int main (int argc, char *argv[])
Argc and Argv for later expansion.
Detailed Description
The main "runner" file for the overall Compiler Project.
Currently, we only employ a Scanner which constructs a Symbol Table. This is accomplished through an included Administration class.
We use a standard set of files and an Administration and Token Classes to run the base Scanner.
We have a static text file containing our sample PL code in the Root directory. This code is then sent into a string which we forward to our constructors for the scanner and admin.
We use local file for now to speed up testing and debugging. At a later date, it will read it from the argc and argv vars.
This file has no associated header.
Author:
Jordan Peoples, Chad Klassen, Adam Shepley
Date:
January 9th to 31st, 2011
Function Documentation
int main (int argc, char * argv[])
Argc and Argv for later expansion.
Read the file to a stream, then send each line to a String. We append our own newline and attach this to our whole File string. Repeat until we reach the end of the file. This might have scaling issues.
We check to see if there was an input parameter, and use that as the filename We do NOT accept multiple inputs (yet?). Choose the first one if multiple detected. If none, then ask for a file name.
Set the debug flag for ASM output if we see the -g flag.
We could incorporate an error class here, but for now, it is not necessary as this is not a compiler operation
We create our administration object with our file string. It then begins the Scanning process. We could also have some error handling here, but that is not required.
See also:
Admin()
Assembler Part This is where our assembler is called. Only runs if no errors are discovered.
LAST MINUTE HACK JOB.
References Admin::getErrorCount(), runAssembler(), runInterpreter(), and Admin::scan().
void runAssembler (Admin * admin)
Function prototypes.
Operates the Assembler component of the compiler.
Use this function with a corresponding completed Parser code in order to run the Assembler on it. The code is then sent to interpInput.itp
References Assembler::firstPass(), Admin::getASM(), and Assembler::secondPass().
void runInterpreter (bool step)
Main function to run our Interpreter.
Use this function to run the Interpreter on assembled PL code. This assumes that the assembled PL interpreter code is present in a file called interpInput.itp.